CREATE DATABASE CLASS1;

USE CLASS1;

CREATE TABLE TAB_EMP(
ID INT PRIMARY KEY IDENTITY(1,1),
EMP_NAME VARCHAR(50),
EMP_SALARY INT

);

INSERT INTO TAB_EMP(EMP_NAME,EMP_SALARY) VALUES('SUFIYAN',120000);

SELECT * FROM TAB_EMP;

SELECT COUNT(EMP_SALARY) FROM TAB_EMP;

SELECT MIN(EMP_SALARY) FROM TAB_EMP;

SELECT MAX(EMP_SALARY) FROM TAB_EMP;

SELECT AVG(EMP_SALARY) FROM TAB_EMP;
